RMS/urls.py
from http.client import HTTPResponse
from django.contrib import admin
from django.shortcuts import render
from django.urls import include, path
from django.urls import path



from . import views

urlpatterns = [
    
               path('',views.home, name="home" ),
               
               path('login',views.userLogin, name="login" ),
               
               path('logout',views.userLogout, name="logout" ),

               path('register',views.register, name="register" ),

               path('userprofile',views.userprofile, name="userprofile" ),
               
               path('companyprofile',views.companyprofile, name="companyprofile" ),
               
               path('department',views.department, name="department" ),

             
               path('noti',views.noti, name="noti" ),

               
               path('usercv',views.usercv, name="usercv" ),

                 
              path('companies',views.companies, name="companies" ),

              path('Editprof',views.Editprof, name="Editprof" ),

              path('EditJobReq/<int:job_id>/', views.EditJobReq, name='edit_job_req'),

              
              path('Editsection/<int:sec_id>/', views.Editsection, name='Editsection'),

              path('deletejob/<int:job_id>/', views.deletejob, name='deletejob'),

              path('deleteskill/<int:skill_id>/', views.deleteskill, name='deleteskill'),


              
              path('EditSkill/<int:skil_id>/', views.EditSkill, name='EditSkill'),


             path('deleteeducation/<int:edu_id>/', views.deleteeducation, name='deleteeducation'),

             
             path('Editeducation/<int:edu_id>/', views.Editeducation, name='Editeducation'),

              path('deleteexpeience/<int:exp_id>/', views.deleteexpeience, name='deleteexpeience'),


              path('Editedexperience/<int:exp_id>/', views.Editedexperience, name='Editedexperience'),


              
              path('deletesection/<int:sec_id>/', views.deletesection, name='deletesection'),

              
              path('deleteproject/<int:Project_id>/', views.deleteproject, name='deleteproject'),


              path('Editproject/<int:project_id>/', views.Editproject, name='Editproject'),

              
              path('deletecertificate/<int:certificate_id>/', views.deletecertificate, name='deletecertificate'),


              path('Editcertificate/<int:cer_id>/', views.Editcertificate, name='Editcertificate'),
              
               path('changepassword',views.changepassword, name="changepassword" ),

               path('Editcvinfo',views.Editcvinfo, name="Editcvinfo" ),

               path('usereducation',views.usereducation, name="usereducation" ),

                path('addusereducation',views.addusereducation, name="addusereducation" ),

                path('userexperience',views.userexperience, name="userexperience" ),

                path('adduserexperience',views.adduserexperience, name="adduserexperience" ),

                path('usercertificates',views.usercertificates, name="usercertificates" ),

                path('addusercertificates',views.addusercertificates, name="addusercertificates" ),

                path('userprojects',views.userprojects, name="userprojects" ),

                path('addproject',views.addproject, name="addproject" ),

                path('edituserbio',views.edituserbio, name="edituserbio" ),

                path('uservolant',views.uservolant, name="uservolant" ),

                path('editusercontact',views.editusercontact, name="editusercontact" ),

                path('userskills',views.userskills, name="userskills" ),

               path('addskills',views.addskills, name="addskills" ),

               
               path('addsection',views.addsection, name="addsection" ),
                
               path('JobRequirements/',views.JobRequirements, name="JobRequirements" ),

               path('NewJob/',views.NewJob, name="NewJob" ),

               path('Status/<int:job_id>/', views.Status, name='Status'),

               path('jobsStatus/', views.jobsStatus, name='jobsStatus'),

               path('JobsHistory/',views.JobsHistory, name="JobsHistory" ),
               

               path('EditCompanyProf',views.EditCompanyProf, name="EditCompanyProf" ),

               
               path('profileinfo',views.profileinfo, name="profileinfo" ),


               path('userinfo',views.userinfo, name="userinfo" ),

                path('welcome',views.welcome, name="welcome" ),
                path('similarity_form',views.similarity_form, name="similarity_form" ),
                path('similarity_result',views.similarity_result, name="similarity_result" ),

                

                path('companydepartment/<int:department_id>/', views.companydepartment, name='companydepartment'),

                path('applicantsdepartment', views.applicantsdepartment, name='applicantsdepartment'),

                path('companyPro/<int:company_id>/',views.companyPro, name="companyPro" ),

                path('companyPro/<int:company_id>/<int:job_id>/', views.companyPro, name='companyPro'),

                path('applicantprof/<int:applicant_id>/',views.applicantprof, name='applicantprof' ),
                
                path('applicantprof/<int:applicant_id>/<int:educations_id>/',views.applicantprof, name='applicantprof' ),

                
                path('usersections', views.usersections, name='usersections'),


                

               path('dashboard',views.dashboard, name="dashboard" ),

                path('deleteapplicant/', views.deleteapplicant, name='deleteapplicant'),
                path('delete_company/', views.delete_company, name='delete_company'),
                 path('delete_department/',views.delete_department, name='delete_department'),
                 path('addApplicantForAdmin/', views.addApplicantForAdmin, name='addApplicantForAdmin'),
                 path('addDepartmentForAdmin/', views.addDepartmentForAdmin, name='addDepartmentForAdmin'),
                   path('add_department/', views.add_department, name='add_department'),
                   path('companiesForAdmin/',views.companiesForAdmin, name='companiesForAdmin'),
                   path('applicantsForAdmin/',views.applicantsForAdmin, name='applicantsForAdmin'),
                   path('departmentForAdmin/',views.departmentForAdmin, name='departmentForAdmin'),
                   path('jobForAdmin/',views.jobForAdmin, name='jobForAdmin'),
                    path('editjobreqdash/<int:job_id>/',views.editjobreqdash, name='editjobreqdash'),
                     path('deletejobdash/<int:job_id>/', views.deletejobdash, name='deletejobdash'),
                     path('JobRequirementsdash/',views.JobRequirementsdash, name="JobRequirementsdash"),
                     path('cv_evaluation/', views.cv_evaluation, name='cv_evaluation'),                 
                     path('test/',views.education_data, name="test"),
                      path('apply_job/<int:job_id>/', views.apply_job, name='apply_job'),

                     path('home/', views.home, name='home'),

         path('company/<int:company_id>/follow_unfollow/', views.follow_unfollow_company, name='follow_unfollow_company'),
           path('followers/', views.followers, name='followers'),

] 


#urlpatterns += static[settings.MEDIA_URL , document_root =settings.MEDIA_ROOT]

cv/urls.py
from http.client import HTTPResponse
from django.contrib import admin
from django.urls import path,include 
from django.http import HttpResponse
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('RMS.urls'))
]

if settings.DEBUG:
  urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

RMS/models.py
from django.db import models
from django.contrib.auth.models import Group,User




 
class Department(models.Model):
    id = models.AutoField(primary_key=True)
    name=models.CharField(max_length=30,null=True)
    
    def __str__(self):
        return self.name
    
    


class company(models.Model):
    id = models.AutoField(primary_key=True)
    name= models.CharField(max_length=100,null=True)
    email=models.CharField(max_length=100,null=True)
    location=models.CharField(max_length=1000,null=True)
    describtion=models.CharField(max_length=1000,null=True)
    companytype=models.CharField(max_length=100,null=True)
    about=models.CharField(max_length=1000,null=True)
    website=models.CharField(max_length=100,null=True)
    phone=models.CharField(max_length=20,null=True)
    companyphoto=models.ImageField(blank=True,null=True,default="company.png")
    user=models.OneToOneField(User,null=True,on_delete=models.CASCADE)
    department = models.ForeignKey(Department, on_delete=models.CASCADE,null=True)
    followers = models.ManyToManyField(User, related_name='followed_companies', blank=True)


    def __str__(self):
       return str(self.name) if self.name else ''
    

    def get_number_of_companies():
        return company.objects.count()
   
  



class Applicant(models.Model):
    id = models.AutoField(primary_key=True)
    name= models.CharField(max_length=20,null=True)
    email=models.CharField(max_length=100,null=True)
    phone= models.CharField(max_length=20,null=True)
    jobname=models.CharField(max_length=100,null=True)
    userphoto=models.ImageField(blank=True,null=True,default="user.png")
    biography=models.CharField(max_length=1000,null=True)
    about=models.CharField(max_length=1000,null=True)
    location=models.CharField(max_length=40,null=True)
    birthdate=models.DateField(max_length=40,null=True)
    volanteering=models.CharField(max_length=1000,null=True)
    user=models.OneToOneField(User,null=True,on_delete=models.CASCADE)
    department = models.ForeignKey(Department, on_delete=models.CASCADE,null=True)
    def __str__(self):
         return str(self.name) if self.name else ''
    
    def get_number_of_applicants():
        return Applicant.objects.count()

 


class skils(models.Model):
   
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=255, null=True)
    applicant = models.ManyToManyField(Applicant)
    def __str__(self):
        return self.name

 
class project(models.Model):
    id = models.AutoField(primary_key=True)
    title=models.CharField(max_length=100,null=True)
    role=models.CharField(max_length=1000,null=True)
    tools=models.CharField(max_length=1000,null=True)
    describtion=models.CharField(max_length=1000,null=True)
    applicant = models.ManyToManyField(Applicant)    
     
    def __str__(self):
        return self.title




 
class workexperience(models.Model):
    id = models.AutoField(primary_key=True)
    companyworked=models.CharField(max_length=100,null=True)
    jobworked=models.CharField(max_length=1000,null=True)
    describtion=models.CharField(max_length=1000,null=True)
    applicant = models.ForeignKey(Applicant, on_delete=models.CASCADE,null=True) 
    
    def __str__(self):
        return self.id




from django.db import models
from django.utils import timezone

class job(models.Model):
    id = models.AutoField(primary_key=True)
    salary = models.CharField(max_length=20, null=True)
    title = models.CharField(max_length=30, null=True)
    location = models.CharField(max_length=40, null=True)
    education = models.CharField(max_length=1000, null=True)
    workexperience = models.CharField(max_length=1000, null=True)
    technicalskills = models.CharField(max_length=1000, null=True)
    achievements = models.CharField(max_length=1000, null=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    start_date = models.DateField(null=True, blank=True)
    end_date = models.DateField(null=True, blank=True)
    deletion_time = models.TimeField(null=True, blank=True)
    is_active = models.BooleanField(default=True) 
    companies = models.ManyToManyField('company')
    applicants = models.ManyToManyField('Applicant')
    number_of_positions = models.IntegerField(default=1)  # New field
    

    def __str__(self):
        return self.title

    class Meta:
        get_latest_by = 'created_at'

    @staticmethod
    def get_number_of_jobs():
        return job.objects.count()

    def is_active_job(self):
        today = timezone.now().date()
        return self.is_active and self.start_date <= today <= self.end_date




class OtherSection(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=255)
    describtion=models.CharField(max_length=1000,null=True)
    applicant = models.ForeignKey(Applicant, on_delete=models.CASCADE,null=True)
    def __str__(self):
        return self.name



class certificate(models.Model):
    id = models.AutoField(primary_key=True)
    place=models.CharField(max_length=1000,null=True)
    major=models.CharField(max_length=1000,null=True)
    about=models.CharField(max_length=1000,null=True)
    applicant = models.ForeignKey(Applicant, on_delete=models.CASCADE,null=True)
   
    def __str__(self):
        return self.major
          
          

class education(models.Model):
    
    id = models.AutoField(primary_key=True)
    title=models.CharField(max_length=1000,null=True)
    degree=models.CharField(max_length=1000,null=True)
    major=models.CharField(max_length=1000,null=True)
    fromto=models.CharField(max_length=1000,null=True)
    applicant = models.ForeignKey(Applicant, on_delete=models.CASCADE,null=True)
   
    def __str__(self):
        return self.title
          

class cv(models.Model):
   
    def __str__(self):
        return self
    

class Item(models.Model):
    def __str__(self):
        return self






class jobstatus(models.Model):
    company = models.ForeignKey(company, on_delete=models.CASCADE)
    applicant = models.ForeignKey(Applicant, on_delete=models.CASCADE)
    job = models.ForeignKey(job, on_delete=models.CASCADE)
    percentage = models.FloatField(default=0)

    def __str__(self):
         return str(self.job) if self.job else ''

class Notification(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    message = models.CharField(max_length=255)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.message    

RMS/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.models import User
from  django.contrib.auth.forms import UserCreationForm
from .models import  Applicant , company
from .models import *

class CreateNewUser(UserCreationForm):
    class Meta:
      model = User 
      
      fields = ['username' ,'email' ,'password1' ,'password2']


class ApplicantForms(ModelForm):
    class Meta:
      model = Applicant
      fields ="__all__"
      exclude = ['user'  , 'skills' ]



class CompanyForms(ModelForm):
    class Meta:
      model = company
      fields ="__all__"
      exclude = ['user','jobs', 'location']
      


class CreateNewjob(ModelForm):
    class Meta:
      model = job 
      fields ="__all__"
      exclude = ['companies','created_at','applicants']


class Createnoti(ModelForm):
    class Meta:
      model = Notification 
      fields ="__all__"
      exclude = ['timestamp']


class CreateNewjobAdmin(ModelForm):
    class Meta:
      model = job 
      fields ="__all__"
      exclude = ['created_at','applicants']


class JobForm(ModelForm):
    class Meta:
        model = job
        fields = '__all__' 
        exclude = ['companies','created_at','applicants']



class projectForm(ModelForm):
    class Meta:
        model = project
        fields = '__all__' 
        exclude = ['applicant']


class skilsForm(ModelForm):
    class Meta:
        model = skils
        fields = '__all__' 
        exclude = ['applicant']


class workexperienceForm(ModelForm):
    class Meta:
        model = workexperience
        fields = '__all__' 
        exclude = ['applicant']



class educationForm(ModelForm):
    class Meta:
        model = education
        fields = '__all__' 
        exclude = ['applicant']



class certificateForm(ModelForm):
    class Meta:
        model = certificate
        fields = '__all__' 
        exclude = ['applicant']






class ApplicantinfoForms(ModelForm):
    class Meta:
      model = Applicant
      fields ="__all__"
      exclude = ['user'  , 'skills' , 'about','volanteering','department']




class ApplicantbioForms(ModelForm):
    class Meta:
      model = Applicant
      fields ="__all__"
      exclude = ['user'  , 'name','volanteering','department','email','phone','jobname'
                 ,'userphoto','biography','location','birthdate','volanteering','department']




class ApplicantcontactForms(ModelForm):
    class Meta:
      model = Applicant
      fields ="__all__"
      exclude = ['user'  ,'volanteering','department','phone','jobname'
                 ,'userphoto','biography','volanteering','department','about']




class ApplicantvolForms(ModelForm):
    class Meta:
      model = Applicant
      fields ="__all__"
      exclude = ['user'  ,'about', 'name','biography','department','email','phone','jobname'
                 ,'userphoto','biography','location','birthdate','department']




class copamyinfo(ModelForm):
    class Meta:
      model = company
      fields ="__all__"
      exclude = ['user','companyphoto' ]
      
    
      


class userInfo(ModelForm):
    class Meta:
      model = Applicant
      fields ="__all__"
      exclude = ['user' ,'userphoto']



class OtherSectionForm(forms.ModelForm):
    class Meta:
        model = OtherSection
        fields ="__all__"
        exclude = ['applicant' ]




class AddDepartmentForm(forms.ModelForm):
    class Meta:
        model = Department
        fields = ['name']        

RMS/templates/RMS/EditSkill.html
{% extends 'RMS/main.html' %}




{% block content %}




<div class="container"   style="margin-top:50px;">


    <div class="card info" style="margin-left: 100px;margin-left: 250px;background-color: rgb(255,255,255,0.1);" >
        <div class="card-body" style="margin-bottom: 60px; width: 100%;">

        <h1 style="color:white" > Edit Skill</h1>
            <form  method="POST" enctype="multipart/form-data" >
               
               

                <div class="row "style="width:900px ;" >
                    <div class="col-lg-8">
                        
                  <form id="profileForm" method ="POST" action = "" enctype = "multipart/form-data" style="padding-left:200px;">
                   <div class = "form-group">
                     {% csrf_token %}
                  {% for field in form %}
                        <label class="form-label">{{ field.label_tag }}</label>
                        {{ field }}
                    {% endfor %}
                   </div>
                       <br>    
           <div class="input-field"style="width:600px;">
                <input type="submit" class="submit" value="Update">
            </div>
                     </form>

             
                    </div>
                </div>
            </form>
        </div>
    </div>
    
</div>

<style>
   
    .form-group label {
        font-size: 20px;
         color:white;
    }
  
  
      .form-group input,
    .form-group select,
    .form-group textarea {
        height: 45px;
    width: 700px;
    border: none;
    outline: none;
    border-radius: 30px;
    color: #fff;
    padding: 0 0 0 42px;
    background: rgba(255,255,255,0.1);
    }
.submit{
    border: none;
    border-radius: 30px;
    font-size: 15px;
    height: 45px;
    outline: none;
    width: 20%;
    background: rgba(255,255,255,0.7);
    cursor: pointer;
    transition: .3s;
}
.submit:hover{
    box-shadow: 1px 5px 7px 1px rgba(0, 0, 0, 0.2);
}
.input-field .input{
    height: 45px;
    width: 20%;
    border: none;
    outline: none;
    border-radius: 30px;
    color: #fff;
    padding: 0 0 0 42px;
    background: rgba(255,255,255,0.1);
}
</style>
    


{% endblock %}

RMS/templates/RMS/Editcvinfo.html
{% extends 'RMS/main.html' %}




{% block content %}


  

<div class="container" style="margin-top:100px;margin-left:200px;"  >
    <div class = "card" style="width:50rem; margin-left: 150px;background-color: rgb(255,255,255,0.1);">
        <img src="{{request.user.applicant.userphoto.url}}" class="img-fluid avatar-xxl rounded-image" alt="" style="height: 160px; width:155px; margin-left: 320px; margin-top: 20px;">
        <div class = "card-body">
            <form method ="POST" action = "" enctype = "multipart/form-data">
                <div class = "form-group">
                 {% csrf_token %}
                  {% for field in form %}
                        <label class="form-label">{{ field.label_tag }}</label>
                        {{ field }}
                    {% endfor %}
                </div>
                  <br>    
           <div class="input-field"style="width:600px;">
                <input type="submit" class="submit" value="Update">
            </div>
             </form>

          </div>
            </div>
        </div>


<style>
   
    .form-group label {
        font-size: 20px;
         color:white;
    }
  
  
      .form-group input,
    .form-group select,
    .form-group textarea {
        height: 45px;
    width: 700px;
    border: none;
    outline: none;
    border-radius: 30px;
    color: #fff;
    padding: 0 0 0 42px;
    background: rgba(255,255,255,0.1);
    }
.submit{
    border: none;
    border-radius: 30px;
    font-size: 15px;
    height: 45px;
    outline: none;
    width: 20%;
    background: rgba(255,255,255,0.7);
    cursor: pointer;
    transition: .3s;
}
.submit:hover{
    box-shadow: 1px 5px 7px 1px rgba(0, 0, 0, 0.2);
}
.input-field .input{
    height: 45px;
    width: 20%;
    border: none;
    outline: none;
    border-radius: 30px;
    color: #fff;
    padding: 0 0 0 42px;
    background: rgba(255,255,255,0.1);
}
</style>


{% endblock %}

RMS/templates/RMS/Editprof.html
{% extends 'RMS/main.html' %}




{% block content %}


  

<div class="container" style="margin-top:100px;margin-left:200px;" >
    <div class = "card" style="width:50rem; margin-left: 150px; background-color: rgb(255,255,255,0.1);">
        <img src="{{request.user.applicant.userphoto.url}}" class="img-fluid avatar-xxl rounded-image" alt="" style="height: 160px; width:155px; margin-left: 320px; margin-top: 20px;">
        <div class = "card-body">
            <form method ="POST" action = "" enctype = "multipart/form-data">
                <div class = "form-group">
                 {% csrf_token %}
                  {% for field in form %}
                        <label class="form-label">{{ field.label_tag }}</label>
                        {{ field }}
                    {% endfor %}
                </div>
                
           <div class="input-field" style="width:600px;">
                <input type="submit" class="submit" value="Save">
            </div>
             </form>


        </div>
            </div>
        </div>


<style>
   
    .form-group label {
        font-size: 20px;
         color:white;
    }
  
  
      .form-group input,
    .form-group select,
    .form-group textarea {
        height: 45px;
    width: 700px;
    border: none;
    outline: none;
    border-radius: 30px;
    color: #fff;
    padding: 0 0 0 42px;
    background: rgba(255,255,255,0.1);
    }
.submit{
    border: none;
    border-radius: 30px;
    font-size: 15px;
    height: 45px;
    outline: none;
    width: 20%;
    background: rgba(255,255,255,0.7);
    cursor: pointer;
    transition: .3s;
}
.submit:hover{
    box-shadow: 1px 5px 7px 1px rgba(0, 0, 0, 0.2);
}
.input-field .input{
    height: 45px;
    width: 20%;
    border: none;
    outline: none;
    border-radius: 30px;
    color: #fff;
    padding: 0 0 0 42px;
    background: rgba(255,255,255,0.1);
}
</style>


{% endblock %}

RMS/templates/RMS/NewJob.html
{% extends 'RMS/main.html' %}
{% load static %}

{% block content %}
  <link rel="stylesheet", href="{%static 'css/style.css'%}">
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create New Post</title>
    <style>
      body {
        font-family: Arial, sans-serif;
        background-color: #f4f4f4;
        margin: 0;
        padding: 0;
      }
  
      .post-container {
        max-width: 600px;
        margin: 100px auto;
        background-color: #fff;
        padding: 20px;
        border-radius: 8px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
      }
  
      .post-form {
        display: flex;
        flex-direction: column;
      }
  
      .post-form textarea {
        resize: none;
        height: 100px;
        margin-bottom: 20px;
        padding: 20px;
        border: 1px solid #ddd;
        border-radius: 4px;
        font-size: 14px;
      }

      .post-form input{
        resize: none;
        height: 10px;
        width: 100px;
        margin-bottom: 20px;
        padding: 20px;
        border: 1px solid #ddd;
        border-radius: 4px;

      }
  
      .post-form button {
        background-color: #1877f2;
        color: #fff;
        padding: 10px;
        border: none;
        border-radius: 4px;
        cursor: pointer;
        font-size: 16px;
      }
    </style>
    <link rel="stylesheet", href="{%static 'css/style.css'%}">
</head>
<body>
  
    <div class="post-container">
      <h2>Create a New Job</h2>
      <form class="post-form">
        <textarea id="postContent" placeholder="Job Announcement"></textarea>
        <button type="button" onclick="submitPost()">Post</button>
      </form>
    </div>

    <script>
      function submitPost() {
        // In a real-world scenario, you would use JavaScript to handle the form submission,
        // possibly using AJAX to send data to a server for processing.
        // Here, we'll just log the post content to the console for demonstration purposes.
  
        var postContent = document.getElementById('postContent').value;
        console.log('Posted: ', postContent);
  
        // You can add further logic to send the data to the server or perform other actions.
      }
    </script>
</body>
</html>

{% endblock %}

RMS/templates/RMS/testModel.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sentence Similarity Calculator</title>
</head>
<body>
    <h1>Sentence Similarity Calculator</h1>
    <form action="{% url 'cv_evaluation' %}" method="post">
        {% csrf_token %}
       
        <button type="submit">Calculate Similarity</button>
    </form>

    {% if similarities %}
    <div>
        <h2>Similarities:</h2>
        {% for sentence, similarity in similarities %}
            <p>{{ sentence }} - Similarity: {{ similarity }}</p>
        {% endfor %}
    </div>
    {% endif %}
</body>
</html>

RMS/templates/RMS/usereducation.html
{% extends 'RMS/main.html' %}




{% block content %}


<head>
    <style>
    .container{

     margin-left:200px;

    }
        body{
            background-image: url('https://img.freepik.com/free-photo/empty-dark-concrete-wall-room-studio-background-floor-perspective-with-blue-soft-light-displays_1258-108910.jpg?t=st=1706640218~exp=1706640818~hmac=233eecd1d002c02436301c4a535d089f1d85f7cd96b485fb29122268b5443fa3');
          
        }
        .card{
           background-color: rgb(255,255,255,0.1);
            margin-right:40px;
        }
        .span{
            color:white;
        }
        .insideposter{
            margin-bottom: 20px;
            width: 850px;
            margin-left:120px;
            background-color: rgb(255,255,255,0.1);
        }
        .headofedit{
            margin-top: -10px;
        }
        .h4{
            color:white;
        }
            .cta-button2 {
  display: inline-block;
  padding: 10px 20px;
  background-color:rgb(226, 62, 62);
  color: #fff;
  text-decoration: none;
  border-radius: 5px;
  margin-top: 15px;
}
.cta-button1 {
  display: inline-block;
  padding: 10px 20px;
  background-color:#3498db;
  color: #fff;
  text-decoration: none;
  border-radius: 5px;
  margin-top: 15px;
}

    </style>


</head>


<div class="container" style="margin-top:100px; "  >



    <div class="insideposter" style="height:80px; ">
        <h1 class="headofedit" style="color:white"> Edit Education</h1>
    </div>
   

    <div class="card info" style="background-color: rgb(255,255,255,0.1); margin-top: 20px; " >
        <div class="card">

                
            <div class="card-body"style="   background-color: rgb(255,255,255,0);" >
                <div  style="margin: 15px 20px 10px 20px;">
                    <div class="d-flex justify-content-between align-items-center mb-4">
                        <h4 class="card-title mb-0" style="color:white;">Education</h4>
                        <a class="btn " href="{% url 'addusereducation' %}" role="button" style="margin-top: 20px; background: rgba(255,255,255,0.7);">Add New</a>

                    </div>
                    <ul class="list-unstyled mb-0">
                        <!-- Education Entry 1 -->
                         {% for education in request.user.applicant.education_set.all %}
                        <li style="list-style: none; margin-bottom: 20px; padding: 15px; border: 1px solid #ddd; border-radius: 8px; position: relative;">
                             <div style="display: inline-block; margin-left: 750px;">

                             
 
                                               <a href="{% url 'Editeducation' education.id %}" class="cta-button1" style=" height:45px;margin-left:-150px; margin-top:0px; ">Edit</a>
                                              
                                         
                                           
                                     </div> 
                           
                             <h3 style="color:white">{{ education.title }}</h3>
                           <p class="font-size-13 mb-2" style="color: black; font-size: 20px;"><span style="color: white; font-size: 18px;">Degree: </span>{{ education.degree }}</p>
                           <p class="font-size-13 mb-2" style="color:black; font-size: 20px;"><span style="color: white; font-size: 18px;">Major: </span>{{ education.major }}</p>
                           <p class="font-size-13 mb-2" style="color: black; font-size: 20px;"><span style="color: white; font-size: 18px;">From-To: </span>{{ education.fromto }}</p>

                                              <div>
                                              
                                              <form method="post" action="{% url 'deleteeducation' education.id %}">
                                              {% csrf_token %}
                                              <input type="submit" class="cta-button2" style="width: 90px; background-color:  rgb(240, 20, 18); margin-left:565px;margin-top:-60px; " value="Delete">
                                               </form>
                                               </div>
                                             
                        </li>
                        {% endfor %}
                      </ul>
                </div>
            </div><!-- end card-body -->
          </div><!-- end card -->    

     </div>
             
</div>




{% endblock %}